//
// Created by rts on 07.02.2022.
//

#ifndef RADIO_SIGNALMAN_LORA_RUSSIA_RAILWAYS_BRIGADE_CHIEF_H
#define RADIO_SIGNALMAN_LORA_RUSSIA_RAILWAYS_BRIGADE_CHIEF_H

#include "lora_russia_railways_common.h"


#define QUEUE_LEN_IN_ELEMENTS 10

#define CURRENT_DEVICE_NUM 2
#define DURATION_TIME_MSEC (SLOT_TIME_MSEC*(CURRENT_DEVICE_NUM-1))

#define BUTTON_DISABLE_ALARM_GPIO_PORT "GPIOC"
#define BUTTON_DISABLE_ALARM_GPIO_PIN 13
#define BUTTON_LEFT_TRAIN_PASSED_GPIO_PORT "GPIOC"
#define BUTTON_LEFT_TRAIN_PASSED_GPIO_PIN 13
#define BUTTON_RIGHT_TRAIN_PASSED_GPIO_PORT "GPIOC"
#define BUTTON_RIGHT_TRAIN_PASSED_GPIO_PIN 13


void brigade_chief_proc_task(void);
void brigade_chief_modem_task(void);
#endif //RADIO_SIGNALMAN_LORA_RUSSIA_RAILWAYS_BRIGADE_CHIEF_H
